x-service-common: &service-common
  extra_hosts:
    - "host.docker.internal:host-gateway"
  networks:
    - default

x-kafka-dependency: &kafka-dependency
  kafka:
    condition: service_healthy

x-kafka-env: &kafka-env
  KAFKA_BOOTSTRAP_SERVERS: munchies-kafka:9092

services:
  order-service:
    <<: *service-common
    container_name: munchies-order-service
    build:
      context: order-service/build/docker/main
    image: munchies-order-service:latest
    ports: [ "8081:8080" ]
    depends_on:
      <<: *kafka-dependency
      munchies-mongo-order-service:
        condition: service_healthy
    environment:
      <<: *kafka-env
      MONGODB_URI: mongodb://munchies-mongo-order-service:27017/order-service

  user-service:
    <<: *service-common
    container_name: munchies-user-service
    build:
      context: user-service/build/docker/main
    image: munchies-user-service:latest
    ports: [ "8082:8080" ]
    depends_on:
      <<: *kafka-dependency
      munchies-mongo-user-service:
        condition: service_healthy
    environment:
      <<: *kafka-env
      JWT_SECRET: blastimus_prime
      MICRONAUT_ENVIRONMENTS: prod
      GATEWAY_SERVICE_URL: http://gateway-service:8080
      PAYMENT_SERVICE_URL: http://payment-service:8080
      MONGODB_URI: mongodb://munchies-mongo-user-service:27017/user-service

  payment-service:
    <<: *service-common
    container_name: munchies-payment-service
    build:
      context: payment-service/build/docker/main
    image: munchies-payment-service:latest
    ports: [ "8083:8080" ]
    depends_on:
      <<: *kafka-dependency
      munchies-mongo-payment-service:
        condition: service_healthy
    environment:
      <<: *kafka-env
      USER_SERVICE_URL: http://user-service:8080
      MONGODB_URI: mongodb://munchies-mongo-payment-service:27017/payment-service

  notification-service:
    <<: *service-common
    container_name: munchies-notification-service
    build:
      context: notification-service/build/docker/main
    image: munchies-notification-service:latest
    ports: [ "8084:8080" ]
    depends_on:
      <<: *kafka-dependency
      munchies-mongo-notification-service:
        condition: service_healthy
    environment:
      <<: *kafka-env
      MONGODB_URI: mongodb://munchies-mongo-notification-service:27017/notification-service

  table-reservation-service:
    <<: *service-common
    container_name: munchies-table-reservation-service
    build:
      context: table-reservation-service/build/docker/main
    image: munchies-table-reservation-service:latest
    ports: [ "8085:8080" ]
    depends_on:
      <<: *kafka-dependency
      munchies-mongo-table-reservation-service:
        condition: service_healthy
    environment:
      <<: *kafka-env
      MONGODB_URI: mongodb://munchies-mongo-table-reservation-service:27017/table-reservation-service

  gateway-service:
    <<: *service-common
    container_name: munchies-gateway-service
    build:
      context: gateway-service/build/docker/main
    image: munchies-gateway-service:latest
    ports: [ "8086:8080" ]
    depends_on:
      <<: *kafka-dependency
      munchies-mongo-gateway-service:
        condition: service_healthy
    environment:
      <<: *kafka-env
      JWT_SECRET: blastimus_prime
      USER_SERVICE_URL: http://user-service:8080
      MONGODB_URI: mongodb://munchies-mongo-gateway-service:27017/gateway-service
