{
  "branches": ["master"],
  "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
       # TODO "@semantic-release/changelog",
      "@semantic-release/git",
      [
        "@semantic-release/github",
        {
          "assets": [
            {
              "path": "scripts/deploy.sh",
              "label": "deploy.sh"
            }
          ]
        }
      ]
  ]
}