/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "munchies"

pluginManagement {
  includeBuild("build-logic")
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
  id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.0.30"
  id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

gitHooks {
  preCommit {
    tasks("spotlessCheck")
  }
  commitMsg { conventionalCommits() }
  createHooks(overwriteExisting = true)
}

include("commons")
include("user-service")

