/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "munchies"

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

plugins {
  id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.0.30"
}

gitHooks {
  commitMsg { conventionalCommits() }
  createHooks(overwriteExisting = true)
}

include("commons")

