apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-mongo-pvc
  namespace: notification-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
