serviceName: restaurant-service
namespace: restaurant-service

image:
  repository: restaurant-service

service:
  type: NodePort

env:
  - name: MICRONAUT_ENVIRONMENTS
    value: "k8s,prod"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
  - name: MONGODB_URI
    value: "mongodb://restaurant-mongodb.restaurant-service.svc.cluster.local:27017/restaurant-service"

autoscaling:
  enabled: true

mongodb:
  enabled: true
  databaseName: restaurant-service
