serviceName: user-service
namespace: user-service

image:
  repository: user-service

service:
  type: NodePort

env:
  - name: MICRONAUT_ENVIRONMENTS
    value: "k8s,prod"
  - name: MONGODB_URI
    value: "mongodb://user-mongodb.user-service.svc.cluster.local:27017/user-service"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
  - name: JWT_SECRET
    value: "blastimus_prime"
  - name: GATEWAY_SERVICE_URL
    value: "http://gateway-service.gateway-service.svc.cluster.local:8080"
  - name: PAYMENT_SERVICE_URL
    value: "http://payment-service.payment-service.svc.cluster.local:8080"

autoscaling:
  enabled: true

mongodb:
  enabled: true
  databaseName: user-service
