apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: table-reservation-mongo-pvc
  namespace: table-reservation-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
