package com.munchies.order.domain.model

import com.munchies.commons.UUIDEntityId

/**
 * Represents the unique identifier for an Order entity.
 *
 * This class extends the UUIDEntityId, which provides a UUID-based identifier.
 * If no value is provided during instantiation, a new UUID will be generated by default.
 *
 * @constructor Creates an OrderId with the specified value or generates a new UUID if no value is provided.
 * @param value The string representation of the UUID. Defaults to a newly generated UUID.
 */
class OrderId(value: String = newId()) : UUIDEntityId(value)
