apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-mongo-pvc
  namespace: restaurant-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
