x-mongo-healthcheck: &mongo-healthcheck
  test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
  interval: 5s
  timeout: 3s
  retries: 10
  start_period: 5s

services:
  munchies-order-mongo:
    image: mongo:7.0
    container_name: munchies-order-mongo
    ports: [ "27018:27017" ]
    volumes: [ "mongo_order_data:/data/db" ]
    healthcheck: *mongo-healthcheck

  munchies-user-mongo:
    image: mongo:7.0
    container_name: munchies-user-mongo
    ports: [ "27019:27017" ]
    volumes: [ "mongo_user_data:/data/db" ]
    healthcheck: *mongo-healthcheck

  munchies-payment-mongo:
    image: mongo:7.0
    container_name: munchies-payment-mongo
    ports: [ "27020:27017" ]
    volumes: [ "mongo_payment_data:/data/db" ]
    healthcheck: *mongo-healthcheck

  munchies-notification-mongo:
    image: mongo:7.0
    container_name: munchies-notification-mongo
    ports: [ "27021:27017" ]
    volumes: [ "mongo_notification_data:/data/db" ]
    healthcheck: *mongo-healthcheck

  #  munchies-table-reservation-mongo:
  #    image: mongo:7.0
  #    container_name: munchies-table-reservation-mongo
  #    ports: [ "27022:27017" ]
  #    volumes: [ "mongo_table_reservation_data:/data/db" ]
  #    healthcheck: *mongo-healthcheck

  munchies-restaurant-mongo:
    image: mongo:7.0
    container_name: munchies-restaurant-mongo
    ports: [ "27024:27017" ]
    volumes: [ "mongo_restaurant_data:/data/db" ]
    healthcheck: *mongo-healthcheck

volumes:
  mongo_order_data:
  mongo_user_data:
  mongo_payment_data:
  mongo_notification_data:
  mongo_table_reservation_data:
  mongo_restaurant_data:
