on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Npm install
        run: npm install

      - name: Prepare OpenAPI docs
        run: bash ./gradlew prepareOpenApiSpecs

      - name: Generate OpenAPI docs
        run: bash ./scripts/generate-openapi-docs.sh

      - name: Generate Kotlin docs
        run: bash ./gradlew dokkaGenerateHtml

      - name: Move Dokka docs
        run: mv build/dokka/html/ docs/pages/kotlin/

      # TODO build typescript typedoc docs
      # TODO move generated docs to docs/pages/typescript/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/pages/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5