on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write  # Required for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Npm install
        run: npm install

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Check version for release
        id: check-version
        shell: bash
        run: |
          GIT_VERSION=$(git describe --tags --exact-match HEAD || echo '')
          if [ -n "$GIT_VERSION" ]; then
            echo "version=$(echo $GIT_VERSION | sed 's/^v//')" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare to publish to npm
        if: steps.check-version.outputs.version != ''
        run: |
          bash ./gradlew clean jsNodeProductionLibraryDistribution

      - name: Publish to npm
        if: steps.check-version.outputs.version != ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bash ./scripts/publish/npm.sh

      # TODO maybe push to npm
      # TODO maybe publish to maven central
      # TODO maybe push to docker hub


      # TODO include the deploy script to release files